### ISSUE TITLE
 Error 0 Contrôleur invalide : user

### ISSUE THREAD

**Issue by philou5672** [chdemko/joomla-external-login#21]
Bonjour,

Je n'arrive pas à me logger sur le serveur cas j'ai cette erreur récurente 
"0 Contrôleur invalide : user"
. J'ai activer l'auto login.

Help me please!!

**Comment by chdemko** [comment]
Pourriez-vous être plus explicite? qu'avez-vous installé activé, entré comme informations....

Ch.D

**Comment by philou5672** [comment]
Bonjour et merci pour réactivité.

Je vien de résoudre mon problème qui était tout simplement le composant ARTIO Joomsef.
En le désactivant  la connexion CAS à fonctionnée.

Je pense que le composant devait filter les variables  j'ai pas creusé mais de toute façon je ne compte plus utilisé joomsef.

Bravo pour votre travail

Une idée: il serait bien d'automatiser la connexion lorsque l'on provient d'un site  en l'occurence  d'une plateforme académique ou l'on est déja authentifié. ( pas de clic sur un bouton)

**Comment by chdemko** [comment]
C'est prévu dans les paramètres de chaque serveur
