### ISSUE TITLE
Full name xpath ?

### ISSUE THREAD

**Issue by philou5672** [chdemko/joomla-external-login#22]
Bonjour,

Comment récupérer les attributs qui dans ce type de schéma

<property
                        <map>
                                <entry key="sn" value="sn" />
                                <entry key="givenName" value="givenName" />
                                <entry key="mail" value="mail" />
                                <entry key="uid" value="uid" />
                                <entry key="eduPersonAffiliation" value="eduPersonAffiliation" />
                                <entry key="groupMembership" value="groupMembership" />
                        </map>
                </property

Pour le user pas de souci mais pour les autres je ne vois pas

pouvez-vous m'aider?

merci

**Comment by chdemko** [comment]
Votre message semble incomplet.

**Comment by philou5672** [comment]
Bonjour oui effectivement
j'ai ce bean en xml:
 <bean id="attributeRepository" 
                class="org.jasig.services.persondir.support.StubPersonAttributeDao">
                <property name="backingMap">
                        <map>
                                <entry key="sn" value="sn" />
                                <entry key="givenName" value="givenName" />
                                <entry key="mail" value="mail" />
                                <entry key="uid" value="uid" />
                                <entry key="eduPersonAffiliation" value="eduPersonAffiliation" />
                                <entry key="groupMembership" value="groupMembership" />
                        </map>
                </property>
        </bean>

je souhaite récupérer les attributs mail et givenName

Biensur je n'y arrive pas!!
Merci d'avance

**Comment by chdemko** [comment]
Pourriez-vous m'afficher un exemple de réponse de votre serveur CAS pour un succès?

**Comment by philou5672** [comment]
Bonjour,

et merci

voici le schéma de réponse que j'ai dans mes logs ( j'ai volontairement caché le user:
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
<cas:authenticationSuccess>
<cas:user>prxxxxx</cas:user>
</cas:authenticationSuccess>
</cas:serviceResponse>
merci de votre aide

**Comment by chdemko** [comment]
Visisblement, votre serveur CAS n'exporte pas les attributs dans sa réponse...

**Comment by gregkoron** [comment]
Hi I have the same issue, however I have tested the response of the CAS server with phpCAS 1.3.0 and I normally receive the attributes that I need. Does anyone have any clue?
