### ISSUE TITLE
AutoLogin?

### ISSUE THREAD

**Issue by sparadrus** [chdemko/joomla-external-login#23]
Bonjour, félicitation pour ce superbe plugin.

Je rencontre un problème, lorsque je me connecte sur jasig 3.5.3 : je ne suis pas automatiquement connecté sur joomla 3.4.5.
La configuration backend de votre extension me semble correcte pour accepter l'autologin. 

Lorsque je clique sur le lien de mon serveur via votre module, cela fonctionne. 
Je suis connecté automatiquement si mon ticket est déjà valide, ou bien je suis renvoyé vers mon sso puis redirigé avec succès sur joomla.

Auriez-vous une idée s'il vous plait? Une URL sur joomla que je peut appeler pour auto-connecter?
Merci par avance

**Comment by chdemko** [comment]
Bonjour, je n'arrive pas à comprendre si cela fonctionne ou pas d'après vos commentaires. Pourrais-je avoir la trace de déboggage (option à activer dans le backend°?

**Comment by sparadrus** [comment]
Bonsoir, si j'attaque directement la page d'acceuil de joomla en étant passé préalablement par mon jasig, je ne suis pas authentifié. Je doit choisir mon serveur dans la liste déroulante de votre module de connexion et cliquer sur connexion. Là ca marche. Mais je souhaiterai passer cet étape et être authentifié directement. C'est possible? Merci

**Comment by chdemko** [comment]
Oui, c'est à régler dans les paramètres du serveur CAS de votre site Joomla.
Voir http://download.chdemko.com/joomla/extensions/external-login/CAS_Plugin-3.0.0-beta1-User_Guide-en-GB.pdf, page 3 (Automatic login)
