### ISSUE TITLE
Autologin failed 

### ISSUE THREAD

**Issue by royalterra** [chdemko/joomla-external-login#24]
Hi I have a cas server 
url:  mydomain:8443
path mylogin

I try to login but I got in the logs 
Info	system-caslogin-autologin	2016-02-17 01:42:50	Autologin failed on server 1
Info	system-caslogin-autologin	2016-02-17 01:42:50	Trying autologin on server 1
Info	system-caslogin-verify	2016-02-17 01:42:50	Successful verification of server 1

Any idea how to solve that 
Thanks

**Comment by chdemko** [comment]
This means that your server is not configured to process autologin for your users. Can you post the configuration of your server 1 here?

**Comment by chdemko** [comment]
Closing this issue as there is no input
