### ISSUE TITLE
Logout redirect

### ISSUE THREAD

**Issue by flashfs** [chdemko/joomla-external-login#26]
I think on new versions of the CAS server the url parameter of logout redirect should be 'service' and not 'url'. See https://jasig.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#logout

"Note: The url parameter defined in the former CAS 2.0 specification is not a valid parameter in CAS 3.0 anymore. CAS Servers MUST ignore given url parameters."

**Comment by chdemko** [comment]
In the code, it's named `service` and not `url`.
