### ISSUE TITLE
Redirection to the article that called the CAS authentication

### ISSUE THREAD

**Issue by shteevy** [chdemko/joomla-external-login#28]
When a user wants to access a URL directly to a page that is behind authentication, he is redirected to the CAS portal. However, after the authentication, the user returns to the site's home page and not to the page from which it was redirected to the CAS portal.
Do you have a method for the user to be redirected to the original page after proper authentication?

Thank you,

Shteevy.

**Comment by chdemko** [comment]
It should work now

**Comment by shteevy** [comment]
Hello,
It works.
Many many thanks,
Steve.
