### ISSUE TITLE
Upgrading RC1 to RC2 error

### ISSUE THREAD

**Issue by shteevy** [chdemko/joomla-external-login#30]
Hello, i'm trying to update RC1 to RC2 but I got this message -> 
![image](https://cloud.githubusercontent.com/assets/2981456/23591753/b9b52cd4-01f5-11e7-9d76-12663127b950.png)

Steve.

**Comment by chdemko** [comment]
Thanks for the report. Could you please try 3.1.0-rc3?

**Comment by shteevy** [comment]
Many thanks it's working perfectly :)
Steve.
