### ISSUE TITLE
CAS Disallow Certain Email Domains from Logging in Easily?

### ISSUE THREAD

**Issue by orware** [chdemko/joomla-external-login#33]
Hi Christophe,

This might be possible already (I'm just not really familiar with XPath) but if not I might be able to submit a pull request for this if I implement it myself, but it would be nice if we could disallow certain email domains from being able to login to a Joomla site via the CAS plugin?

In our case we have a specific email domain for students so it would be easiest to just disallow them from being able to login completely on a site that's intended for staff only simply by checking the email domain.

The other potential option for other schools that use the same email domain for staff and students would be to filter by a group but we don't currently do that on our end (though it would be nice to have group names turned into Joomla Groups potentially...I haven't played with the groups features yet in the CAS Plugin).

**Comment by chdemko** [comment]
Hi Omar, happy to see you here.

You can upload a list of users for a server and disallow automatic login for that server. This should solve your issue.

**Comment by orware** [comment]
Thanks for the update, but I'm not sure if that would be a workable solution in our case (e.g. there are always new students coming in so needing to import a disallowed list on a regular basis probably wouldn't be the easiest thing to maintain over the long term). I never realized you worked for a university though so probably a lot of the issues you've ran into over there (such as CAS authentication) are probably similar to ones I've had to work with too. Do you guys have a similar issue/situation at the University that you handle differently?

**Comment by chdemko** [comment]
In fact, I'm an associate professor in my university. I develop the extension in the hope it will be usefull for us. Unfortunately, my university continue to use [SPIP](http://www.spip.net/en_rubrique25.html) :(

For your issue, we might develop a white/black list using regexp to specify for a server?

**Comment by chdemko** [comment]
@orware See https://github.com/chdemko/joomla-external-login/tree/3.1.1.x for this feature

**Comment by orware** [comment]
Thanks for the update Christophe, I just downloaded the alpha versions and will give them a quick try out right now.
