### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by shteevy** [chdemko/joomla-external-login#35]
Hello Christophe,

The new redirection system is very nice. But i have little problem.

When a user directly loads the address of a specific page of the site, he is redirected because of the "Login redirection" option.

What I would like to do is simply redirect users who connect from the home page to a specific menu link. When the user has entered a direct address to a page, it should continue to be redirected to that page after authentication.

Is it possible ? 
Many thanks for your help,

Steve.

**Comment by chdemko** [comment]
Will do soon

**Comment by chdemko** [comment]
Could you please test the version 3.1.1.0-beta2 which implements your feature?

https://github.com/chdemko/joomla-external-login/tree/3.1.1.x

**Comment by shteevy** [comment]
Hello Christophe. 

The links to pkg_externallogin-3.1.1.0-beta2.zip and plg_system_caslogin-3.1.1.0-beta2.zip are broken.

Steve.

**Comment by chdemko** [comment]
Oups, I forgot to upload the files. Done!

**Comment by shteevy** [comment]
Hello Christophe.
On my Joomla 3.6.5 :

- When "don't redirect" is set on "Yes" and a menu link defined into "Login redirection" => Redirection not OK from the homepage
- When "don't redirect" is set on "No" and a menu link defined into "Login redirection" => Redirection OK from the homepage and  from everywhere (direct URL)

In the two configurations, when I load a direct URL to a page that require authentication, i'm not redirected to this URL a good authentication.
Steve.

**Comment by chdemko** [comment]
I don't understand your issue

**Comment by chdemko** [comment]
I think I've understood what you mean. See 3.1.1.0-rc2

https://github.com/chdemko/joomla-external-login/tree/3.1.1.x

**Comment by shteevy** [comment]
Hello Christophe,
Sorry for this comment sent very late and not very understandable.

With version 3.1.1.0-rc2:

- When I select the following configuration:

![image](https://cloud.githubusercontent.com/assets/2981456/23897535/d94105f0-08ad-11e7-9d00-449497856298.png)

---> No redirection from the HomePage
---> No redirection from a specific URL to this specific URL after authentication :

![image](https://cloud.githubusercontent.com/assets/2981456/23897590/08ebea0e-08ae-11e7-8846-691daef02542.png)

---> No redirection from the HomePage
---> Redirection from a specific URL to this specific URL after authentication : OK

In the two cases, I cannot get the redirection working from the homepage.

Steve.

**Comment by chdemko** [comment]
Is it in a module, in a menu item, in a server configuration or in the component?

**Comment by shteevy** [comment]
Hello Christophe, it's in the server configuration. 
I tried with the component configuration but nothing is working for me. I tried on 2 others Joomla installation and same effect too.

Steve.

**Comment by chdemko** [comment]
And are you doing exactly (filling the url in the browser, clicking on a menu item, ...)

**Comment by shteevy** [comment]
When I select the following configuration:

![image](https://cloud.githubusercontent.com/assets/2981456/23925904/b1f18cf4-0911-11e7-9985-61222fbacc22.png)

1. Clear the cache of browser
2. Just log from the from the homepage of the website using the module. Result : no redirection
3. Disconnection and clear cache 
4. Trying to load a direct url (for example www.site.com/news.html)
5. The page ask me to authenticate, i use the module again
6. After succesfull authentication, i'm not redirected to the page example www.site.com/news.html

in the other config : 

![image](https://cloud.githubusercontent.com/assets/2981456/23925990/1eab2c42-0912-11e7-8609-8b0fecafcb7a.png)

1. Clear the cache of browser
2. Just log from the from the homepage of the website using the module : no redirection
3. Disconnection and clear cache
4. Trying to load a direct url (for example www.site.com/news.html)
5. the page ask me to authenticate, i use the module again
6. After succesfull authentication, i'm correctly redirected to the page example www.site.com/news.html


Steve.

**Comment by chdemko** [comment]
Did you refresh the site front page in step 3?

**Comment by shteevy** [comment]
Yes i refreshed it. I can give you access to my website if you want to make some tests.
Steve.

**Comment by chdemko** [comment]
See 3.1.1.0-rc3

**Comment by shteevy** [comment]
Strange comportement : I have to put "Don't force redirect" on "no" if I want to be redirected from the home page. After successfull login, i'm on the page "/component/users/?view=login"

Steve.

**Comment by chdemko** [comment]
The better is that you give me access to the website. send at chdemko at gmail dot com

**Comment by shteevy** [comment]
Hello Christophe, did you receive my mail with the informations to access my website ?

**Comment by chdemko** [comment]
Yes thanks, I have some health issues...

**Comment by shteevy** [comment]
Hello Christophe. I hope you are fine. Did you verify the problem on my joomla ? Steve.

**Comment by chdemko** [comment]
Closing this issue as there is no new input
