### ISSUE TITLE
Redirect appending external URL

### ISSUE THREAD

**Issue by flashfs** [chdemko/joomla-external-login#36]
Hi. First of all, nice work on maintaining this component.

I do think there is a small bug with blocked/incorrect/unknown redirection. I've tried to create a invisible menu link with External URLs (actually they are internal .html files). When the the plugin blocks the user, the redirection just appends the path, like: http://www.site.com/index.php?/mypath/file_html&Itemid=414, insted of respecting the behavior of the External URL menu type.

**Comment by chdemko** [comment]
See 3.1.1.0-rc3

**Comment by flashfs** [comment]
I've installed the new version but I get the same error: a 404 component not found because it is still appending the file path to the base site url. I tried switching to an internal Joomla article and it works fine, but the External URL doesn't.
I'm using the Firefox anonymous navigation, Joomla 3.6.5.

**Comment by flashfs** [comment]
Doing some research, I could see that on file /plugins/system/externallogin/externallogin.php the function
```php
JRoute::_('index.php?Itemid=' . $redirect, true)
```
is outputting ```/index.php?https://myexternalurl_com/blockeduser_html=&Itemid=414```

**Comment by chdemko** [comment]
Thanks. Will have a look this WE.

**Comment by chdemko** [comment]
Could you test the new version?

**Comment by chdemko** [comment]
Closing this one as there is no input
