### ISSUE TITLE
Choose server

### ISSUE THREAD

**Issue by shteevy** [chdemko/joomla-external-login#37]
Hello Christophe,

When a single CAS Server is configured and a non-connected user loads a page that require authentication, the user have to "Choose Server".
Do you think it's possible to show only a "connexion buton" when only one server is configured ?

![image](https://cloud.githubusercontent.com/assets/2981456/24019822/e82e7988-0a99-11e7-99d2-57c6a7beb1d3.png)

Many thanks for your help,
Steve.

**Comment by chdemko** [comment]
You can propose a pull request.

**Comment by chdemko** [comment]
Closing this issue as there is no input
