### ISSUE TITLE
Login joomla with CAS

### ISSUE THREAD

**Issue by anhld93** [chdemko/joomla-external-login#39]
Dear sir,
I am very appreciate for what you have done. I have implemented your external project, everything is work very well until i have a problem with login joomla.
1) Enter URL of my website
2) Redirect to CAS server, log in.
3) Redirect back to my website without log in Joomla system.
I do not know if can we log in Joomla system in step 3, like we can get use from JFactory:getUser() after logged CAS server.
Note: i am a newbie in Joomla, so forgive me if i made mistake and sorry for my bad English.
Best regard.

**Comment by chdemko** [comment]
Can you please post here the configuration of your CAS server in Joomla

**Comment by anhld93** [comment]
Dear Sir,
Thank you for replying me.
I found my problem, it is because my mistake in configuring CAS server's SSL certification. After rework, your app works very great. 
As i read on wiki/Cas-login, the login support 2 case of logout: 
+Automatic login To automatically log in a user when he is already logged in on the CAS server.
+Automatic logout To automatically log out a user on the CAS server when he logs out on the Joomla! site.
So may i ask you about scenario: when logout on CAS server, Joomla will log out too ?
Many thank for your support.
Best regard.

**Comment by abow** [comment]
"So may i ask you about scenario: when logout on CAS server, Joomla will log out too ?"

I would like to know the answer to this, too.  Thanks

**Comment by anhld93** [comment]
Dear abow,
Actually it can. I mean when you logout CAS server, joomla should logout too. My problem is when i use BACK_CHANNEL logout, the CAS server can not send the message logout to client (my joomla system). Maybe it is because wrong SSL configure on my Xampp server. You can do FRONT_CHANNEL logout instead, but it work only one time.
Best regard.
