### ISSUE TITLE
Error at step Verify the service

### ISSUE THREAD

**Issue by bluesea88** [chdemko/joomla-external-login#41]
Dear Christophe, 

I install joomla-external-login and CAS Login into my joomla system.
I got the error [Curl error: error setting certificate verify locations].
<i>Could you please help me solve the issue?</i>
The following is the steps I found the error:
- After login CAS server successfully, user could not login into joomla.
- So I checked log in table [externallogin_logs] and found message "Unsuccessful verification of server 1".
- I tried to read code and found that there was error when performing [Verify the service] in file caslogin.php (line 226 -234)
- I trace error by the following code:
 if(curl_errno($curl)){
	  echo 'Curl error: ' . curl_error($curl);
}

<b>ERROR FOUND</b>: Curl error: error setting certificate verify locations: CAfile: cas_server.crt CApath: E:\cashttps://localhost:8443/cas/serviceValidate?ticket=........

<i>Could you please guide me how to configure path for the Certification file?
Thank you so much for your work and your help.</i>

The connection was configured as in the following picture:
![connection_config](https://cloud.githubusercontent.com/assets/26791718/24502093/7e92eb7a-1576-11e7-90bf-d42427ace8b7.JPG)

**Comment by chdemko** [comment]
I think you should inverse path and file

**Comment by chdemko** [comment]
Closing this issue as there is no input
