### ISSUE TITLE
Edit server don't populate form with Joomla 3.7

### ISSUE THREAD

**Issue by alcad** [chdemko/joomla-external-login#42]
Hi Christophe,
editing a server previous saved, all serialized data are not populated in form.
Saving again will overwrite the original data with default data.
This only happens in Joomla 3.7

**Comment by shteevy** [comment]
Hello, I have the same problem.
Have a nice weekend,
Steve

**Comment by greyfoxamine** [comment]
Same problem , 
have a nice day Christophe,

**Comment by greyfoxamine** [comment]
Hi Mr Demko,
The component, in backoffice, don't show values in forms, but it save them in database. The connection is OK on frontend.
So, it's just a display problem, a reading of database, in BO.
Have you any idea to resolve this ?
Thanks,
Regards

**Comment by sparadrus** [comment]
With greyfoxamine, we think its a problem of reading database...  dissociate value of externallogin table in different row maybe fix the problem... Regards

**Comment by sparadrus** [comment]
Sorry i cant edit my previous reply. So its maybe a pb of collation or separator because the first value is  correctly show, the name of server. But next values who dont reading. Amine say the component also work, its true the module on frontend connect great to sso. Cordialement

**Comment by PeterTHM** [comment]
It's because getItem() in com_externallogin\admin\models\server.php->loadFormData() creates a array in the property 'params' that holds another array called 'data' that finally contains all the attributes for the form.

Previously the params property contained the attributes directly.

**Comment by flashfs** [comment]
Same is happening here with plugin 3.1.1.0-rc3 and Joomla 3.7.4.

**Comment by bakeevdr** [comment]
I removed the load function from administrator/components/com_externallogin/tables/server.php in joomla 3.8.8 and everything worked.

**Comment by bakeevdr** [comment]
This is the trouble in all versions of joomla 3.x 

The error occurs because of the double conversion of JRegistry. 
the first administrator/components/com_externallogin/tables/server.php. (function load)
the second is libraries\src\MVC\Model\AdminModel.php (function getItem)

the fix is sufficient in administrator/components/com_externallogin/models/server.php (function loadFormData)
to add a check after line 111
````php
if (empty($data))
		{
			$data = $this->getItem();
			if (isset($data->params['data']))
				$data->params =  $data->params['data'];
		}
````
