### ISSUE TITLE
CAS login plugin no panels after install

### ISSUE THREAD

**Issue by Pest2016** [chdemko/joomla-external-login#44]
I installed plg_system_caslogin-3.1.0.0-rc4 (not the package files) and expected to see some form fields to input the host URL, Port, path to CAS, etc. as you explain here: [https://github.com/chdemko/joomla-external-login/wiki/CAS-Login](url)

However, when I open the plugin there is only a blank screen underneath the plugin title. Is the plugin broken? I am using Ubuntu server, but got same result on my local XAMPP install.

I am trying to get this to work with a university CAS, so I don't think I need to install the package (got same SQL errors described by blandman).

Thank you!

**Comment by Pest2016** [comment]
So there's no way to get this plugin to work?

**Comment by sparadrus** [comment]
Hello, actually it work (update value in database) but when you reopen component, it show blank value. Only name of server it correctly display. But component work on 3.7

**Comment by chdemko** [comment]
You should install the package
