### ISSUE TITLE
Error accessing External Login Component

### ISSUE THREAD

**Issue by shteevy** [chdemko/joomla-external-login#46]
Hello,

I made a fresh install of the RC4 into a French Joomla installation (3.7.5). When i try to enter the "External Login Menu" > "Users" or "Servers" (but not in Log), I get this message
![image](https://user-images.githubusercontent.com/2981456/29769423-97a491a0-8bea-11e7-9928-b30a21878995.png)"

Many thanks,

Steve.

**Comment by chdemko** [comment]
Can you try with Joomla! 3.8?
