### ISSUE TITLE
Populate form with response variables

### ISSUE THREAD

**Issue by kostas27** [chdemko/joomla-external-login#51]
Hello, I use external login module and plugin successfully in my joomla site to authenticate at a third SSO party and return to the "registered" area of the site, where I have some forms. However, I cannot use any response variables in my  forms. For example, I need the surname of the user to populate a relative form field, in the sso system the surname is descibed as "sn". Can you give me a hint as for how I should declare this variable and other variables I need in the Full name xpath field in:  Servers Manager: Edit --> Attributes, so I can access them and use the user's data?
I use joomnla 3.8.2.
Thanks for any help.

**Comment by chdemko** [comment]
I can't help you for that issue.
