### ISSUE TITLE
Login redirection is not working correctly in Joomla 3.8.12.

### ISSUE THREAD

**Issue by Kitsune18** [chdemko/joomla-external-login#56]
I'm having trouble getting login redirection working, it keeps redirecting users to the user's profile page in Joomla and which has a Edit Profile button shown on the screen.   I do not want users sent to the Joomla profile page they should be redirected to a specific Joomla article but it will not send users there after they log in. . I have the correct login redirection page selected in external login but it does not appear to be working correctly for me.

I have installed the latest external-login v3.1.2.0 on Joomla 3.8.12 and we're using the CAS 3.1.2.0 plugin as well.

Thank you!

**Comment by chdemko** [comment]
See #55
