### ISSUE TITLE
Error logging in after upgrading to 3.1.2.2

### ISSUE THREAD

**Issue by eddiekonczal** [chdemko/joomla-external-login#58]
After upgrading the External Login Package and CAS Login Plugin from 3.1.1.0-rc3 to 3.1.2.2, I can no longer login to the front-end or back-end via CAS.  Here is the error I receive:

Error
Login ist not activated for this user

This occurs on Joomla! 3.9.1.  Here is the system information:

Setting | Value
-- | --
 
PHP Built On | Linux webdesign 4.4.155-94.50-default #1 SMP Tue Sep 11 13:04:00 UTC 2018 (bc8c7c0) x86_64
Database Type | mysql
Database Version | 5.5.39
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.7
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0 SeaMonkey/2.48

Thanks,
Eddie

**Comment by chdemko** [comment]
Log in with a super user in the backend (/administrator/index.php?option=com_externallogin&view=users) and verify that the user can use External Login

**Comment by eddiekonczal** [comment]
Thanks, that worked!


Is there a way to make "External Login = authorized" the default setting for new users, or will each new Joomla! user need to be separately authorized within the External Login component?


Thanks again,

Eddie


------------------

Eddie Konczal

Unit Computing Manager

School of Arts and Sciences, IT Services

Rutgers, The State University of New Jersey

640 Bartholomew Road, Room 109

Busch Campus
Piscataway, NJ 08854
848-932-6456

konczal@sas.rutgers.edu

http://sas.rutgers.edu


________________________________

**Comment by chdemko** [comment]
Normally, activate "Auto-register" in the server details (administrator/index.php?option=com_externallogin&view=server&layout=edit&id=1)

**Comment by eddiekonczal** [comment]
Thanks; I activated "Auto-register" in the server details, but it doesn't seem to work as expected.


If I create a Joomla! account with a username matching the user's organization account in CAS, the user cannot log in unless I  then "Enable/Disable Global" in External Login.


If the username does not exist in Joomla!; External Login will auto-register the user, but I then need to enable Joomla! login for that user.


What I'm hoping to accomplish is to create Joomla! accounts for new users, with usernames matching their organizational usernames (for CAS), without having to perform the additional step of running "Enable/Disable Global" in External Login after every new account is created.  Is this possible?


Thanks,

Eddie


------------------

Eddie Konczal

Unit Computing Manager

School of Arts and Sciences, IT Services

Rutgers, The State University of New Jersey

640 Bartholomew Road, Room 109

Busch Campus
Piscataway, NJ 08854
848-932-6456

konczal@sas.rutgers.edu

http://sas.rutgers.edu


________________________________

**Comment by chdemko** [comment]
You can upload new users via http://localhost/~chdemko/joomla3812/administrator/index.php?option=com_externallogin (try the dowload button to see the file format)

**Comment by eddiekonczal** [comment]
I should have clarified that what we would like to do is have users created within Joomla's native "Users > Manage" (i.e. via index.php?option=com_users&view=users ) automatically be enabled in CAS.  is this possible or not?

Thanks,
Eddie

**Comment by chdemko** [comment]
Currently, it's possible for all users or none
`administrator/index.php?option=com_externallogin&view=users`

Use Enable/Disable Global

But it's not possible to do it automatically... Perhaps a plugin (to be written) could help...

**Comment by eddiekonczal** [comment]
Since the original problem was resolved by this process:

- Components > External Login
- Click "Users" on the left
- Click "Enable/Disable Global" at the top
- Click "Activate for all users"

I'm closing this issue.
