### ISSUE TITLE
Unsuccessful verification of server 1 

### ISSUE THREAD

**Issue by Mika17420** [chdemko/joomla-external-login#62]
Bonjour,
le package est-il toujours d'actualité ?
Après son installation et paramétrage je me retrouve avec des logs :

Warning | system-caslogin-verify | 2019-07-17 09:48:24 | Unsuccessful verification of server 1
-- | -- | -- | --
d’où peut venir le problème.
Mon paramétrage semble correct.
Merci de votre aide

**Comment by chdemko** [comment]
le package est toujours d'actualités, peut-être les paramètres ne sont-ils pas correct. Activez les logs et analysez les réponses.

**Comment by Mika17420** [comment]
Bonjour,
Je me pose une question concernant l'utilisation du CAS avec Joomla (joomla-external-login).
J'ai mis en place un serveur qui semble fonctionnel. Je n'ai pas installer le serveur LDAP (est-ce nécessaire ?)
Niveau logs :
Info | system-caslogin-autologin | 2019-09-03 10:03:51 | Trying autologin on server 1
-- | -- | -- | --
Info | system-caslogin-verify | 2019-09-03 10:03:51 | Successful verification of server 1
Comment voir si les tickets sont générés correctement lors de la connexion de l'adhérent.
A savoir que l'utilisation du CAS ici ne sert qu'a utiliser les identifiants d'un site internet à un autre site internet.
Merci pour votre aide
